#!/usr/bin/env bash
filename=$(ls /usr/share/man/man{1..8} /usr/local/share/man/man{1..8} | grep '[0-9]$' | fzf)
man_number="${filename##*.}"
program="${filename%.*}"

man() {
  env \
    LESS_TERMCAP_mb=$(printf "\e[1;31m") \
    LESS_TERMCAP_md=$(printf "\e[1;31m") \
    LESS_TERMCAP_me=$(printf "\e[0m") \
    LESS_TERMCAP_se=$(printf "\e[0m") \
    LESS_TERMCAP_so=$(printf "\e[1;44;33m") \
    LESS_TERMCAP_ue=$(printf "\e[0m") \
    LESS_TERMCAP_us=$(printf "\e[1;32m") \
      man "$@"
}

man $man_number $program
