#!/usr/bin/env bash
# TODO: make this into a node cli

set -euo pipefail
students_file=$HOME/.students

if [[ ${1:-} == '-r' ]]; then 
  voice=$(say -v ? | cut -d ' ' -f 1 | tail -n $((RANDOM % 47)) | head -n 1)
else 
  voice=daniel
fi 

student_count=$(cat $students_file | wc -l | sed 's/ *//')

student=$( tail -n $((RANDOM % student_count)) $students_file  | head -n 1 )

[[ $student == '' ]] && student='whoops there was an error'

echo $student
say -v "$voice" $student 
