#!/bin/bash

# PURPOSE:
# open alacritty in currnt working dir :] 
# * only works when creating a new alacritty terminal when an alacritty terminal is in focus
# * does not support TMUX
#
# NOTE:
# this exec is assisted by plug/terminal, which sets the terminal title 
# to __XOXO__:$PWD each time the shell loads a line

RESULT=$(xdotool getactivewindow getwindowname)
CHECK=$(echo $RESULT |cut -d ':' -f 1)
WORKDIR=$(echo $RESULT |cut -d ':' -f 2)

if [[ $CHECK = '__XOXO__' ]]; then 
  if [ -e $WORKDIR ]; then
    alacritty --working-directory $WORKDIR
  else 
    alacritty --working-directory $HOME/workspace
  fi
else 
  alacritty --working-directory $HOME/workspace
fi

