#!/usr/bin/env bash

export TRASH_DIR=$HOME/.local/share/Trash/files
mkdir -p $TRASH_DIR 

# TODO make this way better
# https://github.com/jrobinson52/command-line-trash/blob/master/trash
if [[ -d $TRASH_DIR ]]; then
  for f in "$@"; do
    name=$(basename "$f")
    if [[ -d "$f" ]];then
      source_path=$(readlink -f $f)
      date=$(date +'%Y-%m-%d_%H-%M')
      output_path="$TRASH_DIR/${date}_${RANDOM}_${name}"
      mv "$f" "$output_path" --force
      touch "$output_path"
    else
      checksum=$(shasum "$f" | cut -d ' ' -f 1 | sed -e 's/[[:space:]]*$//')
      output_path="$TRASH_DIR/${checksum}_${name}"
      mv "$f" "$output_path" --force
      touch "$output_path"
    fi
  done
else
  echo ERROR: no trash bin
  >&2 exit 1
fi
