#!/usr/bin/env bash

if [[ -d $HOME/.trash ]]; then 
  for f in "$@"; do
    name=$(basename "$f")
    if [[ -d "$f" ]];then 
      date=$(date +'%Y-%m-%d_%H-%M')
      output_path="$HOME/.trash/${date}_${RANDOM}_${name}"
      mv "$f" "$output_path" --force
      touch "$output_path"
    else 
      checksum=$(shasum "$f" | cut -d ' ' -f 1 | sed -e 's/[[:space:]]*$//')
      output_path="$HOME/.trash/${checksum}_${name}"
      mv "$f" "$output_path" --force
      touch "$output_path"
    fi 
  done
else 
  echo ERROR: no trash bin 
  >&2 exit 1
fi
