#!/usr/bin/env bash
source $MOLD_ROOT/plug/wm_style.sh
CURRENT=$(bspc query -T -m| jq '.name' | tr '"' ' ' | xargs)
echo $CURRENT

RIGHT_DESKTOP_NAME_LIST=("a" "b" "c" "d")
LEFT_DESKTOP_NAME_LIST=("1" "2" "3" "4")

if [[ $CURRENT = $WM_STYLE_MONITOR_RIGHT ]]; then
  bspc node -d ${RIGHT_DESKTOP_NAME_LIST[$1]} --follow
else
  bspc node -d ${LEFT_DESKTOP_NAME_LIST[$1]} --follow
fi
