#!/bin/bash
PADDING=$(bspc config top_padding)

if [[ $PADDING -eq $WM_STYLE_BAR_HEIGHT ]];then 
  polybar-msg cmd hide
  bspc config top_padding 0
else
  polybar-msg cmd show
  bspc config top_padding $WM_STYLE_BAR_HEIGHT
fi

