#!/bin/bash

CURRENT=$(bspc query -T -m| jq '.name')

if [[ $CURRENT = "\"$WM_STYLE_MONITOR_LEFT\"" ]];then
  bspc monitor -f $WM_STYLE_MONITOR_RIGHT
else 
  bspc monitor -f $WM_STYLE_MONITOR_LEFT
fi
