"ui.background" = {bg = "main_background"}
"ui.background.separator" = {bg = "main_background", fg = "gray5"}

"ui.cursor" = {bg =  "gray6",  fg =  "black"}
"ui.cursor.normal" = {bg =  "gray6",  fg =  "black"}
"ui.cursor.insert" = {bg =  "gray4",  fg =  "gray8"}
"ui.cursor.select"  = {bg = "gray6" , fg =  "black"}
"ui.cursor.primary" = {bg =  "gray8",  fg =  "black"}
"ui.cursor.primary.normal" = {bg =  "gray8",  fg =  "black"}
"ui.cursor.primary.insert" = {bg =  "gray5",  fg =  "gray8"}
"ui.cursor.primary.select"  = {bg = "gray8" , fg =  "black"}
"ui.cursor.match" = {bg = "gray3", fg  = "gray7"}
"ui.debug.breakpoint" = {fg = "blue"}
"ui.debug.active" = {fg = "green"}
# "ui.gutter" = {}
# "ui.gutter.selected" = {}
"ui.linenr" = "gray4"
"ui.linenr.selected" = "gray7"
"ui.statusline" = {bg = "statusline", fg = "gray7"}
"ui.statusline.inactive" =  {bg = "gray1", fg =  "gray4"}
# "ui.statusline.normal" = {bg = "statusline", fg = "gray7"}
"ui.statusline.insert" =  {bg = "lack", fg =  "gray9"}
"ui.statusline.select" =  {bg = "gray9", fg =  "black"}
# "ui.statusline.separator" =  {bg = ""}
"ui.popup" =  {bg = "popup_background", fg  = "gray6"} # doc  popups
# "ui.popup.info" =  {}  # which key  popups
"ui.picker.header" = {fg = "gray4"}
"ui.window" =  {  fg = "gray6"} # border lines  seperating splits

"ui.help" =  {bg  = "popup_background",  fg = "gray6"} # description  box   for  commands

"ui.text" = {fg = "gray8"}
"ui.text.focus" = {bg = "gray3"} # selected  picker  text
"ui.text.info" = {fg = "gray8"} 
"ui.text.directory" = {fg = "gray6"}
"ui.virtual.ruler" = {bg = "#171717"}
# "ui.virtual.whitespace" = {}
# "ui.virtual.indent-guide" = {}
"ui.virtual.inlay-hint" = "gray4"
"ui.virtual.inlay-hint.parameter" = "orange"
"ui.virtual.inlay-hint.type" = "red"
"ui.virtual.wrap"   =  {fg = "gray4"}
"ui.highlight" = {bg = "gray3"}
# "ui.highlight.frameline" = {}
"ui.cursorline.primary" =  {bg = "#171717"}
"ui.cursorline.secondary" =  {bg = "#171717"}
"ui.cursorcolumn.primary" =  {bg = "#171717"}
"ui.cursorcolumn.secondary" =  {bg = "#171717"}
"ui.menu" = {bg =  "popup_background", fg =  "gray6"}
"ui.menu.selected" =  {bg = "gray8",  fg  = "black"}
"ui.menu.scroll" =  {bg = "gray3",  fg  = "gray4"}
"ui.selection" = {bg = "#252525"}
"ui.selection.primary" = {bg = "#252525"}
"tabstop" = "gray5" # snippit  placeholder

# gutter
"warning" = "orange"
"error" = { fg = "red"}
"info"  = "gray4"
"hint" = "gray4"

"ui.virtual.jump-label" =  {fg = "yellow"}
"special"  =  "gray6b"

# editing area
"diagnostic" = {fg = "gray5"}
"diagnostic.warning" = {fg = "gray5", underline = {color = "gray4", style = "line"}}
"diagnostic.error" = {fg = "gray5", underline = {color = "gray4", style = "curl"}}
# "diagnostic.unnecessary" = {  modifiers = ["dim"]} 
"diagnostic.deprecated" = { fg = "gray5", modifiers = ["crossed_out"]} 

"tag" = {fg =  "gray8"}
"string" = {  fg = "yellow"} 
# "string.special" = "red"
"constant.character.escape" = { fg = "gray6"}
"comment" =  "comment"  
"variable" = {fg = "gray8"}
"variable.other.memeber" = {fg = "gray8"}
"variable.parameter" =  "gray8" 
"constant" = "gray7"
"constant.builtin" = "gray6" 
"function" = {fg = "gray6b"}
"keyword" =  "#ccbbaa"
"keyword.control.return" =  "orange"
# "keyword.control.exception" =  "#ccbbaa"
"keyword.operator" = "gray6"
"operator" = "gray6"
"punctuation"  = "gray6"
"type" = {fg = "gray7"}
"type.enum" = "gray7"

"diff" = {fg = "gray3"}
"diff.plus" = {fg = "green"}
"diff.minus" = {fg = "red"}  
"diff.delta" = {fg = "blue"}
"diff.delta.conflict" = {fg = "yellow"}
"diff.plus.gutter" = {fg = "gray4"}
"diff.minus.gutter" = {fg = "red", modifiers = ["dim"]}
"diff.delta.gutter" = {fg = "gray4", modifiers = ["dim"]}

"markup.heading" = { fg = "gray5"}
"markup.heading.1" = { fg = "gray6"}
"markup.list" = { fg = "gray4" }
"markup.quote" = { fg = "gray5"  }
"markup.raw" = {fg = "lack"}
"markup.raw.block" = {fg = "lack",  modifiers = ["bold"]}
"markup.link" = "blue"
"markup.link.url" = { fg = "green"}
"markup.bold" = { modifiers = ["bold"]}
"markup.italic" = { modifiers = ["italic"]}
"markup.strikethrough" = { modifiers = ["crossed_out"]}

[palette]
lack = "#708090"
luster = "#deeeed"
# orange = "#ffaa88"
orange = "#ccaa88"
yellow = "#abab77"
green = "#789978"
blue = "#7788aa"
red = "#d70000"
black = "#000000"
gray1 = "#080808"
gray2 = "#191919"
gray3 = "#2a2a2a"
gray4 = "#444444"
gray5 = "#555555"
gray6 = "#7a7a7a"
gray6b = "#909090"
gray7 = "#aaaaaa"
gray8 = "#cccccc"
gray9 = "#dddddd"
main_background = "#101010"
menu_background = "#191919"
popup_background = "#1a1a1a"
statusline = "#242424"
comment = "#4a4a4a"
exception = "#505050"
special_keyword = "#666666"
param = "#8e8e8e"
whitespace = "#202020"


