export WM_STYLE_BAR_HEIGHT=20
export WM_STYLE_PADDING_NONE=0
export WM_STYLE_PADDING_SMALL=5
export WM_STYLE_PADDING_LARGE=45
export WM_STYLE_MONITOR_LEFT='DisplayPort-2'
export WM_STYLE_MONITOR_RIGHT='HDMI-A-0'
