#!/bin/bash

killall sxhkd polybar conky

sxhkd &
polybar left &
polybar right & 
conky &

bspc monitor DisplayPort-2 -d 1 2 3 4
bspc monitor HDMI-A-0 -d 1 2 3 4
bspc monitor -f HDMI-A-0

bspc config border_width 4
bspc config active_border_color '#999999'
bspc config normal_border_color '#ffffff'
bspc config focused_border_color '#feea00'
bspc config window_gap $WM_STYLE_PADDING_SMALL
bspc config top_padding $WM_STYLE_BAR_HEIGHT

bspc config split_ratio 0.5
