#!/bin/bash

source $HOME/.config/mold/plug/wm_style.sh

killall sxhkd polybar conky

sxhkd &
polybar left &
polybar right & 
conky &
ibus-daemon -drx &
xinput set-prop 14 293 0.8




bspc monitor $WM_STYLE_MONITOR_LEFT -d 1 2 3 4
bspc monitor $WM_STYLE_MONITOR_RIGHT -d 1 2 3 4
bspc monitor -f HDMI-A-0

bspc config top_padding $WM_STYLE_BAR_HEIGHT

bspc config active_border_color $WM_STYLE_ACTIVE_COLOR
bspc config normal_border_color $WM_STYLE_NORMAL_COLOR
bspc config focused_border_color $WM_STYLE_FOCUSED_COLOR

bspc config window_gap $WM_STYLE_GAP_NONE
bspc config border_width $WM_STYLE_BORDER_EXTRA_SMALL

bspc config split_ratio 0.5
